### ISSUE TITLE
Race hazard in ProcessGroup.Go method 

### ISSUE THREAD

**Issue by JoeReid** [rickb777/process#1]
There is a subtle [race hazard](https://github.com/rickb777/process/blob/master/process.go#L52-L55) which makes use of the `ProcessGroup` type in parallel unsafe.

While not a bug per se, the fact that the type is not thread-safe should be more clearly documented (or the race hazard fixed).

For clarity, the hazard specifically is the null check of the `sync.WaitGroup`.
**Initial** calls in parallel to `ProcessGroup.Go` will race on the creation of the `WaitGroup` and in worse case over-write eachother's `WaitGroup` in the object, potentialy leading to returning prematurely from `ProcessGroup.Join`

I believe moving the `WaitGroup` initialization to the constructor will fix the race.

As far as regression testing goes, I think that calling these methods in parallel (in a test executed with the `-race` flag) may be enough for the [race detector](https://golang.org/doc/articles/race_detector.html) to pick up this issue.

**Comment by rickb777** [comment]
Thanks for your observation. I tried running the race analyser, without success, However, I'm sure your diagnosis is right.

**Comment by rickb777** [comment]
Fixed in v1.2.2
